from typing import Optional, Dict, Any
from src.providers.base_provider import BaseProvider


class AbuseIPDBProvider(BaseProvider):
    """
    Concrete implementation for the AbuseIPDB API.
    Specializes in IP reputation and tracking abusive IP addresses.
    """

    def name(self) -> str:
        return "AbuseIPDB"

    def enrich_ip(self, ip: str) -> Optional[Dict[str, Any]]:
        """Queries AbuseIPDB for a specific IP address."""
        url = "https://api.abuseipdb.com/api/v2/check"
        headers = {"Accept": "application/json", "Key": self.api_key}
        params = {"ipAddress": ip, "maxAgeInDays": 90}

        result = self._make_request("GET", url, headers=headers, params=params)

        # If the request was successful, extract only the relevant business logic data
        if result and "data" in result:
            data = result["data"]
            return {
                "abuse_confidence_score": data.get("abuseConfidenceScore", 0),
                "total_reports": data.get("totalReports", 0),
                "country": data.get("countryCode", "Unknown"),
            }

        # Return the raw result if it contains an error message generated by the BaseProvider
        return result

    def enrich_hash(self, file_hash: str) -> Optional[Dict[str, Any]]:
        """
        AbuseIPDB does not support file hash enrichment.
        Returns None to explicitly signal lack of support for this IoC type.
        """
        return None
